TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  max_vel_x: 0.26
  min_vel_x: 0.1

  max_vel_theta: 1.82
  min_vel_theta: -1.82
  min_in_place_vel_theta: 0.4

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.05
  vx_samples: 18
  vtheta_samples: 20
  controller_frequency: 20.0

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.8
  gdist_scare: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.5
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_cost_grid_pc: true
  global_frame_id: odom