robot_base_frame: base_footprint
costmap_topic: /explore_costmap/costmap/costmap
costmap_updates_topic: /explore_costmap/costmap/costmap_updates
visualize: true

planner_frequency: 1.0
progress_timeout: 3600.0

potential_scale: 1.0
orientation_scale: 0
gain_scale: 1.0

transform_tolerance: 0.3
min_frontier_size: 0.5